apiVersion: v2
name: pprodb

description: Helm chart for a PostgreSQL database
type: application
version: 0.1.0
appVersion: 1.16.0

keywords:
  - database
  - postgres
  - pprodb
home: https://github.com/marbald/helm-minikube
maintainers:
  - name: Marco Baldelli
    url: https://github.com/wkrzywiec
