ingress:
  name: ingress
  replicaCount: 1
  namespace: dev
  annotations:
    class: nginx
  hosts:
    - host: app.k8s.ppro-dev-local.com
      paths:
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: pproapp
              port: 
                number: 3000
